development:
  host: localhost
  database: postdrop_development

test:
  host: localhost
  database: postdrop_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>
